#!/bin/sh

down() {
pamixer -d 5 --allow-boost --set-limit 200
volume=$(pamixer --get-volume)
[ $volume -gt 0 ] && volume=`expr $volume`
dunstify -a "VOLUME" "Decreasing to $volume%" -h int:value:"$volume" -i audio-volume-low-symbolic -r 2593 -u normal
#canberra-gtk-play -i audio-volume-change -d "changevolume"
}

up() {
pamixer -i 5  --allow-boost --set-limit 200
volume=$(pamixer --get-volume)
[ $volume -lt 200 ] && volume=`expr $volume`
dunstify -a "VOLUME" "Increasing to $volume%" -h int:value:"$volume" -i audio-volume-high-symbolic -r 2593 -u normal
#canberra-gtk-play -i audio-volume-change -d "changevolume"
}

mute() {
pamixer -t
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
esac
